name: C/C++ CI

on:
  push:
    branches: [ "support_openssl_3.1*" ]
  pull_request:
    branches: [ "support_openssl_3.1*" ]

permissions:
  actions: read
  checks: read
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: download SDK
      run: wget https://download.01.org/intel-sgx/sgx-linux/2.24/distro/ubuntu22.04-server/sgx_linux_x64_sdk_2.24.100.3.bin
    - name: install SDK
      run: chmod +x *.bin; echo yes | ./sgx_linux_x64_sdk_2.*.bin
    - name: download OpenSSL code
      run: wget https://www.openssl.org/source/openssl-3.1.5.tar.gz --directory-prefix=openssl_source/
    - name: build SGXSSL
      run: source sgxsdk/environment; cd Linux; make all; DEBUG=1 make all
    - name: run unit test in SIM
      run: source sgxsdk/environment; cd Linux; make -C sgx/test_app/ clean; SKIP_INTELCPU_CHECK=TRUE SGX_MODE=SIM make test      
